# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: vk8434255
# "service" is the name of this project. This will also be added to your AWS resource names.
service: email-sender

provider:
  name: aws
  runtime: python3.12
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: localhost
    httpPort: 3000


functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true
